// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfZNab.Infra.Data;

#nullable disable

namespace SelfZNab.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250906082827_ExtraParams")]
    partial class ExtraParams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SelfZNab.Domain.Models.Torrent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TorrentFile")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Torrents");
                });
#pragma warning restore 612, 618
        }
    }
}
