// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfZNab.Infra.Data;

#nullable disable

namespace SelfZNab.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020154135_MovieTvShowOptionalInDatabase")]
    partial class MovieTvShowOptionalInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SelfZNab.Domain.Models.Torrent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TorrentFile")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Torrent", (string)null);
                });

            modelBuilder.Entity("SelfZNab.Domain.Models.Torrent", b =>
                {
                    b.OwnsOne("SelfZNab.Domain.Models.Movie", "Movie", b1 =>
                        {
                            b1.Property<int>("TorrentId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CatalogId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TorrentId");

                            b1.ToTable("Torrent");

                            b1.WithOwner()
                                .HasForeignKey("TorrentId");
                        });

                    b.OwnsOne("SelfZNab.Domain.Models.TvShow", "TvShow", b1 =>
                        {
                            b1.Property<int>("TorrentId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("CatalogId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Episode")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Season")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TorrentId");

                            b1.ToTable("Torrent");

                            b1.WithOwner()
                                .HasForeignKey("TorrentId");
                        });

                    b.Navigation("Movie");

                    b.Navigation("TvShow");
                });
#pragma warning restore 612, 618
        }
    }
}
