// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfZNab.Infra.Data;


#nullable disable

namespace SelfZNab.Infra.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20250723201559_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

        modelBuilder.Entity("SelfZNab_Api.Models.Media", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Medias");
            });
#pragma warning restore 612, 618
    }
}
